### ISSUE TITLE
LESS 文件中遇到 @-moz-keyframes 不能识别

### ISSUE THREAD

**Issue by thethreeonee** [fouber/static-resource-digest-project#2]
LESS 文件里还有 @-moz-keyframes 之类的东西就不能识别，然后自动退出了
提示：[ERROR] parser.less: Unrecognised input [/Path/To/Less.less:65:0]

**Comment by fouber** [comment]
@celtavonce 

贴一下完整的代码我看看

**Comment by thethreeonee** [comment]
@fouber 
代码如下：

``` less
@keyframes breatharrow
{
0%   {opacity: 0.2;}
25%  {opacity: 0.3;}
50%  {opacity: 0.4;}
100% {opacity: 0.5;}
}

@-moz-keyframes breatharrow /* Firefox */
{
0%   {opacity: 0.2;}
25%  {opacity: 0.3;}
50%  {opacity: 0.4;}
100% {opacity: 0.5;}
}

@-webkit-keyframes breatharrow /* Safari 和 Chrome */
{
0%   {opacity: 0.2;}
25%  {opacity: 0.3;}
50%  {opacity: 0.4;}
100% {opacity: 0.5;}
}

@-o-keyframes breatharrow /* Opera */
{
0%   {opacity: 0.2;}
25%  {opacity: 0.3;}
50%  {opacity: 0.4;}
100% {opacity: 0.5;}
}

.arrow {
  position: absolute;
  left: 50%;
  bottom: 5px;
  color: white;
  font-size: 30px;
  margin-left: -15px;
  opacity: 0.2;

  animation: breatharrow 1s ease-in 1s infinite alternate;
  -moz-animation: breatharrow 1s ease-in 1s infinite alternate; /* Firefox */
  -webkit-animation: breatharrow 1s ease-in 1s infinite alternate;  /* Safari 和 Chrome */
  -o-animation: breatharrow 1s ease-in 1s infinite alternate; /* Opera */
}
```
